=== mustafashakeel/learning/xml/XML in easy steps - Source code/4 - Adding XSD restrictions/number.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- XML in easy steps - Page 62. -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- DECLARE ELEMENTS. -->

<!-- Simple types. -->
<xsd:element name="int" type="xsd:integer" />
<xsd:element name="pos" type="xsd:positiveInteger" /> 
<xsd:element name="neg" type="xsd:nonPositiveInteger" /> 
<xsd:element name="dec" type="xsd:decimal" /> 
<xsd:element name="flt" type="xsd:float" /> 

<!-- Complex types. -->
<xsd:element name="doc" type="docType"/>


<!-- DEFINE STRUCTURE. -->
<xsd:complexType name="docType">
	<xsd:sequence>
		<xsd:element ref="int" maxOccurs="unbounded"/>
		<xsd:element ref="pos" maxOccurs="unbounded"/>
		<xsd:element ref="neg" maxOccurs="unbounded"/>
		<xsd:element ref="dec" maxOccurs="unbounded"/>
		<xsd:element ref="flt" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>
	
</xsd:schema>

=== mustafashakeel/learning/xml/XML in easy steps - Source code/4 - Adding XSD restrictions/number.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- XML in easy steps - Page 62. -->

<doc 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="number.xsd" >

	<!-- Acceptable integer content. -->
	<int>123</int>
	<int>-123</int>
	<int>0</int>

	<!-- Acceptable positive integer content. -->
	<pos>123</pos>
	<!-- But not 0 or -123 -->	

	<!-- Acceptable negative integer content. -->
	<neg>-123</neg>
	<neg>0</neg>

	<!-- Acceptable decimal content. -->
	<dec>12345.67890</dec>
	<dec>0.000</dec>
	<dec>-12345.67890</dec>

	<!-- Acceptable float content. -->
	<flt>0.12345678901234567890123456789</flt>
	<flt>0.00000000000000000000000000000</flt>
	<flt>-0.12345678901234567890123456789</flt>

</doc>
