=== mustafashakeel/learning/xml/XML in easy steps - Source code/4 - Adding XSD restrictions/string.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- XML in easy steps - Page 70. -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- CUSTOM DATA TYPES. -->

<!-- Create a custom data type to restrict string length. -->
<xsd:simpleType name="zipType">
	<xsd:restriction base="xsd:string">
		<xsd:minLength value="5"/>
		<xsd:maxLength value="5"/>
	</xsd:restriction>
</xsd:simpleType>


<!-- DECLARE ELEMENTS. -->

<!-- Simple types. -->
<xsd:element name = "store" type = "xsd:string" />
<xsd:element name = "address" type = "xsd:string" />

<!-- Complex types. -->
<xsd:element name="doc" type="docType"/>
<xsd:element name="zip" type="zipType"/>
	


<!-- DEFINE STRUCTURE. -->
<xsd:complexType name="docType">
	<xsd:sequence maxOccurs="unbounded">
		<xsd:element ref = "store" />
		<xsd:element ref = "address" />
		<xsd:element ref="zip"/>
	</xsd:sequence>
</xsd:complexType>

</xsd:schema>

=== mustafashakeel/learning/xml/XML in easy steps - Source code/4 - Adding XSD restrictions/string.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- XML in easy steps - Page 70. -->

<doc 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="string.xsd" >

<store>Macy's</store>
<address>151 West 34th Street, New York</address>
<zip>10001</zip>

<store>Saks Fith Avenue</store>
<address>611 5th Avenue, New York</address>
<zip>10022</zip>

<store>Bloomingdales</store>
<address>1000 3rd Avenue, New York</address>	
<zip>10022</zip>
	
</doc>
