=== mustafashakeel/learning/xml/XML in easy steps - Source code/3 - Writing XSD schemas/cactus.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- DECLARE ELEMENTS. -->
	
<!-- Simple type. -->
<xsd:element name="name" type="xsd:string"/>

<!-- Complex types. -->
<xsd:element name="doc" type="docType"/>
<xsd:element name="cactus" type="cactusType"/>



<!-- DEFINE STRUCTURES. -->

<!-- Root element sequence structure. -->
<xsd:complexType name="docType">
  <xsd:sequence>
    <xsd:element ref="cactus" maxOccurs="100"/>
  </xsd:sequence>
</xsd:complexType>

<!-- Nested <cactus> element sequence structure. -->
<xsd:complexType name="cactusType">
    <xsd:sequence>
    <xsd:element ref="name"/>
  </xsd:sequence>
  <xsd:attribute name="id" type="xsd:ID" use="required"/>
</xsd:complexType>
	
	
</xsd:schema>

=== mustafashakeel/learning/xml/XML in easy steps - Source code/3 - Writing XSD schemas/cactus.xml
<?xml version="1.0" encoding="UTF-8"?>
 
<!-- XML in easy steps - Page 56. -->

<doc 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cactus.xsd" >

	<cactus id="AZ1">
	  	<name>Arizona Barrel</name>
	</cactus>

	<cactus id="AZ2">
		<name>Arizona Beehive</name>
	</cactus>

	<cactus id="AZ3">
		<name>Arizona Fishhook</name>
	</cactus>

	<cactus id="AZ4">
		<name>Arizona Hedgehog</name>
	</cactus>

	<cactus id="AZ5">
		<name>Arizona Pincushion</name>
	</cactus>

</doc>
