=== mustafashakeel/learning/xml/XML in easy steps - Source code/5 - Using XML namespaces/canon.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema 
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.ineasysteps.com/canon" xmlns:c="http://www.ineasysteps.com/canon" >

<!-- DECLARE ELEMENTS. -->

<!-- Simple type. -->
<xsd:element name = "model" type = "xsd:string" />
<xsd:element name = "item-code" type = "xsd:string" />

<!-- Complex type. -->

<xsd:element name="doc" type="c:docType"/>
<xsd:element name="camera" type="c:cameraType"/>


<!-- DEFINE STRUCTUES. -->

<xsd:complexType name="docType">
	<xsd:sequence>
		<xsd:element ref="c:camera" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>
	
<xsd:complexType name="cameraType">
	<xsd:sequence>
		<xsd:element ref="c:model" />
		<xsd:element ref="c:item-code" />
	</xsd:sequence>
</xsd:complexType>
	

</xsd:schema>

=== mustafashakeel/learning/xml/XML in easy steps - Source code/5 - Using XML namespaces/canon.xml
<?xml version="1.0" encoding="UTF-8"?>
		
<doc 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.ineasysteps.com/canon canon.xsd" 
xmlns = "http://www.ineasysteps.com/canon" >
	
	<camera>
		<model>Canon Sureshot</model>
		<item-code>WP-1</item-code>
	</camera>

	<camera>
		<model>Canon Powershot</model>
		<item-code>G-7</item-code>
	</camera>

	<camera>
		<model>Canon Digital</model>
		<item-code>I-65</item-code>
	</camera>

</doc>
