=== mustafashakeel/learning/xml/XML in easy steps - Source code/5 - Using XML namespaces/nikon.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema 
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.ineasysteps.com/nikon" xmlns:n="http://www.ineasysteps.com/nikon" >

<!-- DECLARE ELEMENTS. -->

<!-- Simple type. -->
<xsd:element name = "version" type = "xsd:string" />
<xsd:element name = "model" type = "xsd:string" />

<!-- Complex type. -->
<xsd:element name="doc" type="n:docType"/>
<xsd:element name="camera" type="n:cameraType"/>


<!-- DEFINE STRUCTURES. -->

<xsd:complexType name="docType">
	<xsd:sequence>
		<xsd:element ref="n:camera" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>
	
<xsd:complexType name="cameraType">
	<xsd:sequence>
		<xsd:element ref="n:version" />
		<xsd:element ref="n:model" />
	</xsd:sequence>
</xsd:complexType>
	

</xsd:schema>

=== mustafashakeel/learning/xml/XML in easy steps - Source code/5 - Using XML namespaces/nikon.xml
<?xml version="1.0" encoding="UTF-8"?>
		
<doc 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.ineasysteps.com/nikon nikon.xsd" 
xmlns = "http://www.ineasysteps.com/nikon" >
	
	<camera>
		<version>Nikon Coolpix</version>
		<model>L1</model>
	</camera>

	<camera>
		<version>Nikon Silver</version>
		<model>D40</model>
	</camera>

	<camera>
		<version>Nikon Digital</version>
		<model>D50</model>
	</camera>	

</doc>
