=== mustafashakeel/learning/xml/XML in easy steps - Source code/7 - Adding XPath expressions/bikes.xsd
<?xml version = "1.0" encoding = "UTF-8" ?>

<!-- XML in easy steps - Page 117. -->

<xsd:schema 
xmlns:xsd = "http://www.w3.org/2001/XMLSchema"
targetNamespace = "http://www.ineasysteps.com/xsd"
xmlns:tns = "http://www.ineasysteps.com/xsd" >

<!-- DECLARE ELEMENTS. -->

<!-- Simple types. -->

<xsd:element name = "make" 	type = "xsd:string" 	/>
<xsd:element name = "model" 	type = "xsd:string" 	/>
<xsd:element name = "ltr" 	type = "xsd:decimal" 	/>
<xsd:element name = "cyl" 	type = "xsd:integer" 	/>
<xsd:element name = "drive" 	type = "xsd:string" 	/>
<xsd:element name = "price" 	type = "xsd:integer"	/>

<!-- Complex types. -->

<xsd:element name = "doc"  	type = "tns:docType" 	/>
<xsd:element name = "item" 	type = "tns:itemType"	/>


<!-- DEFINE STRUCTURES. --> 

<xsd:complexType name = "docType">
	<xsd:sequence maxOccurs = "unbounded">
		<xsd:element ref = "tns:item" 	/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name = "itemType">
	<xsd:sequence>
		<xsd:element ref = "tns:make" 	/>
		<xsd:element ref = "tns:model" 	/>
		<xsd:element ref = "tns:ltr" 	/>
		<xsd:element ref = "tns:cyl" 	/>
		<xsd:element ref = "tns:drive" 	/>
		<xsd:element ref = "tns:price" 	/>
	</xsd:sequence>
	<xsd:attribute name = "id" type = "xsd:string" use = "required" />
</xsd:complexType>

</xsd:schema>

=== mustafashakeel/learning/xml/XML in easy steps - Source code/7 - Adding XPath expressions/bikes.xml
<?xml version = "1.0" encoding = "UTF-8" ?>

<!-- XML in easy steps - Page 117. -->

<?xml-stylesheet type = "text/xsl" href = "sibling.xsl" ?>

<bike:doc 
xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation = "http://www.ineasysteps.com/xsd bikes.xsd"
xmlns:bike = "http://www.ineasysteps.com/xsd">

	<bike:item id = "electraglide">
		<bike:make>Harley Davidson</bike:make>
		<bike:model>Electra Glide</bike:model>
		<bike:ltr>1.584</bike:ltr>
		<bike:cyl>2</bike:cyl>
		<bike:drive>belt</bike:drive>
		<bike:price>16095</bike:price>
	</bike:item>

	<bike:item id = "goldwing">
		<bike:make>Honda</bike:make>
		<bike:model>Gold Wing</bike:model>
		<bike:ltr>1.832</bike:ltr>
		<bike:cyl>6</bike:cyl>
		<bike:drive>shaft</bike:drive>
		<bike:price>19299</bike:price>
	</bike:item>

	<bike:item id = "r1200rt">
		<bike:make>BMW</bike:make>
		<bike:model>R 1200 RT</bike:model>
		<bike:ltr>1.170</bike:ltr>
		<bike:cyl>2</bike:cyl>
		<bike:drive>shaft</bike:drive>
		<bike:price>17075</bike:price>
	</bike:item>

	

</bike:doc>
