=== mustafashakeel/learning/xml/xml schemas/movieschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="movieList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="movie" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="movie">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="xs:string"/>
				<xs:element name="review" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="title">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="rating" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="review">
		<xs:complexType mixed="true">
			<xs:choice>
				<xs:element name="para"/>
				<xs:element name="citation"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mustafashakeel/learning/xml/xml schemas/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<movieList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="movieschema.xsd">
	<movie>
		<title rating="PG">Star Wars</title>
		<rating>
			<![CDATA[
			Fantastic space opera. Fight between good & evil. Ground-breaking special effects.
			]]>
		</rating>
	</movie>
	<movie>
		<title rating="PG-13">Spider-man</title>
	</movie>
	<movie>
		<title rating="PG-13">Mr. &amp; Mrs. Smith</title>
	</movie>
</movieList>
